### ISSUE TITLE
Error: json: cannot unmarshal object into Go struct ...

### ISSUE THREAD

**Issue by p4t0k** [maas/terraform-provider-maas#11]
Hi, 

I got this error when trying to create a simple maas_instance resource:

> maas_instance.one_random_node[0]: Creating...
> ╷
> │ Error: json: cannot unmarshal object into Go struct field VLAN.interface_set.links.subnet.vlan.relay_vlan of type int
> │ 
> │   with maas_instance.one_random_node[0],
> │   on tier5-deployer.tf line 54, in resource "maas_instance" "one_random_node":
> │   54: resource "maas_instance" "one_random_node" {
> │ 
> ╵

This is what I have in my *.tf file. 

> resource "maas_instance" "one_random_node" {
>   count = 1
> //  network_interfaces {
> //    name = "mgmt"
> //    subnet_cidr = "10.147.101.0/24"
> //    ip_address = "10.147.101.111"
> //  }
>   allocate_params {
>     tags = ["ctrl-hv-lab1"]
>   }
>   deploy_params {
>     distro_series = "focal"
>   }
> }

When I uncomment network_interfaces block then I got similar error but related to RAID:

> maas_instance.one_random_node[0]: Creating...
> ╷
> │ Error: json: cannot unmarshal object into Go struct field Machine.raids of type string
> │ 
> │   with maas_instance.one_random_node[0],
> │   on tier5-deployer.tf line 24, in resource "maas_instance" "one_random_node":
> │   24: resource "maas_instance" "one_random_node" {
> │ 
> ╵

It is possible that I just don't use it correctly, but my interpretation of these two sentences from the maas_instance's documentation page

> Provides a resource to deploy and release machines already configured in MAAS, based on the specified parameters. If no parameters are given, a random machine will be allocated and deployed using the defaults. 

... is that I don't need to define and import (if they exist) other low-level resources like maas_machine, maas_space, maas_fabric, maas_vlan, maas_network_interface_link and maas_network_interface_physical, because these were already defined in MAAS WebUI and that's exactly what I need - to be able to add machines in MAAS WebUI, do the basic configuration and then run my deploy script (that will use terraform-provider-maas) and it will deploy it based on tags.  

If this is not a bug, then I would still appreciate a piece of information about what I'm doing wrong. 

MAAS version: 3.1.0
terraform version: v1.1.9 (tried also v1.0.4 with the same result)
go version: go1.15.15 linux/amd64
terraform-provider-maas: latest (master), I tried also dan-sullivan/terraform-provider-maas fork (with the same result as well)

Thank you.

**Comment by cpg1111** [comment]
same as https://github.com/maas/terraform-provider-maas/issues/13, there's a PR up to fix this https://github.com/maas/terraform-provider-maas/pull/14

**Comment by p4t0k** [comment]
Cool, good to see there is a fix already. Thanks.
