### ISSUE TITLE
Deploy machine from terraform and include cloud-init

### ISSUE THREAD

**Issue by leijonatm** [maas/terraform-provider-maas#140]
Hello and thanks for this provider,
I was wondering if it is possible now to use the "Deploy" action in maas on an already commissioned and Ready state machine. Could you add this feature including the option to provide cloud-init script ?

Thank you

**Comment by skatsaounis** [comment]
Hi @leijonatm,

What you ask can be accomplished with the `maas_instance` [resource](https://registry.terraform.io/providers/maas/maas/latest/docs/resources/instance#user_data). Please give it a try. Both the resource description and the `user_data` field contain information about what they are trying to accomplished, if used.

Thank you for opening the issue and more importantly for using our provider. :slightly_smiling_face:
