### ISSUE TITLE
When creating a tag, ability to set kernel options

### ISSUE THREAD

**Issue by RomainL972** [maas/terraform-provider-maas#15]
Hi,

On the documentation, there is a page explaining how to create a tag associated with specific kernel options (https://maas.io/docs/how-to-customise-machines#heading--how-to-set-global-kernel-boot-options)

It would be great if it was possible to create a tag in terraform with the ability to add those kernel options directly, otherwise I have to create the tag manually using the CLI.

**Comment by jurekh** [comment]
Added to internal backlog for resolution.

**Comment by dekarl** [comment]
I'd love to set the XPath definition, too. Thus allowing creation of automatic tags that apply kernel options.

There is a small permission issue with automated tags that has an easy fix
https://discourse.maas.io/t/automatic-tag-not-working/7098

**Comment by skatsaounis** [comment]
Hi @RomainL972 and @dekarl

The new version of the provider `1.3.0` includes the feature of adding `comment`, `definition`, and `kernel_opts` fields to tag resources. Feel free to give it a try. Relevant docs: https://registry.terraform.io/providers/maas/maas/latest/docs/resources/tag

**Comment by dekarl** [comment]
LGTM

Importing a tag with comment and definition (and read-only machines) also imports the machines into the state.

Leading to a plan like this
```
  # maas_tag.tag-4gb will be updated in-place
  ~ resource "maas_tag" "tag-4gb" {
        id         = "4gb"
      ~ machines   = [
          - "gxnnnf",
          - "rpcx88",
        ]
        name       = "4gb"
        # (2 unchanged attributes hidden)
    }
```
But after applying once the next plan does not show the planned action anymore.

Importing a tag with kernel options also worked as expected.
