### ISSUE TITLE
Feature Request: Resource required to enable TLS security protocol on MAAS

### ISSUE THREAD

**Issue by vishvikkrishnan** [maas/terraform-provider-maas#161]
It would be helpful to have a `maas_tls` resource to enable TLS communications for the MAAS API. Currently, this is achieved using the command:

`sudo maas config-tls enable $key $cert --port YYYY`

where `$key`, `$cert`, and `YYYY` are private key, TLS certificate, and the HTTPS port, respectively.

A model maas_tls resource could look like this:

```hcl
resource "maas_tls" "tls_enable" {
  cert     = <tls-cert>
  key      = <private-key>
  port     = <https_port> # e.g. 5443
}
```

**Comment by skatsaounis** [comment]
Hi @vishvikkrishnan

I am afraid that this feature request cannot be implemented. The configuration of TLS is not made through the API. Instead, as it can be observe [here](https://github.com/maas/maas/blob/master/src/maasserver/management/commands/config_tls.py#L50) this is implemented with a Django command. That means you can only run it from region controller.

**Comment by troyanov** [comment]
The API does not provide access to this configuration option simply because transmitting the private key over the network would compromise its security.
