### ISSUE TITLE
Bug: Unable to compose VMs on MAAS machine deployed as LXD host

### ISSUE THREAD

**Issue by vishvikkrishnan** [maas/terraform-provider-maas#162]
provider version: 2.1.0

After deploying a MAAS-enlisted machine as LXD host using the `maas_vm_host` resource, it is not possible to compose a new VM on top of the newly deployed LXD host. The following error shows when attempting to apply the resource `maas_vm_host_machine`:

```shell
 Error: ServerError: 400 Bad Request ({"cores": ["Ensure this value is less than or equal to 0."], "memory": ["Ensure this value is less than or equal to 0."]})
│ 
│   with maas_vm_host_machine.lxd_machine["node07"],
│   on main.tf line 9, in resource "maas_vm_host_machine" "lxd_machine":
│    9: resource "maas_vm_host_machine" "lxd_machine" {
│ 
```

Terraform config used:
```hcl
resource "maas_vm_host" "lxd" {
  for_each = var.machines

  type    = "lxd"
  machine = each.key
  name    = each.value
}

resource "maas_vm_host_machine" "lxd_machine" {
  for_each = maas_vm_host.lxd

  vm_host = each.value.name
  cores = 1
  memory = 2048

  storage_disks {
    size_gigabytes = 10
  }
}
```

Input Variable:
```hcl
var.machines = {
  "node07" = "lxd-host-1"
}
```

The Terraform state contents show that the core and memory values are 0 while the storage detail is correctly recorded:
```json
{
  "version": 4,
  "terraform_version": "1.7.2",
  "serial": 1,
  "lineage": "45131965-7201-11ef-b54c-f5177fb6bb11",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "maas_vm_host",
      "name": "lxd",
      "provider": "provider[\"registry.terraform.io/maas/maas\"]",
      "instances": [
        {
          "index_key": "node07",
          "schema_version": 0,
          "attributes": {
            "cpu_over_commit_ratio": 1,
            "default_macvlan_mode": "",
            "id": "21",
            "machine": "node07",
            "memory_over_commit_ratio": 1,
            "name": "lxd-host-1",
            "pool": "default",
            "power_address": null,
            "power_pass": null,
            "power_user": null,
            "resources_cores_total": 0,
            "resources_local_storage_total": 94524579840,
            "resources_memory_total": 0,
            "tags": [
              "pod-console-logging"
            ],
            "type": "lxd",
            "zone": "default"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
  ],
  "check_results": null
}
```

GUI approach also fails with the same error.
![image](https://github.com/maas/terraform-provider-maas/assets/44338064/8faaf852-e70c-49a3-9074-b4cfa44b0778)

It should be possible to compose a VM through the MAAS provider on a newly deployed MAAS machine registered as a LXD host.

**Comment by troyanov** [comment]
Hi @vishvikkrishnan 
It might be an LXD related [issue](https://bugs.launchpad.net/maas/+bug/2048399). Which LXD version do you have?

**Comment by skatsaounis** [comment]
I am going to close this since it is not a bug on the provider but on LXD 5.20. MAAS is configured to install `5.21/stable` on the latest minor versions of `3.3`, `3.4` and soon `3.5`. As of 9th of April ,`5.21/stable` is actually pointing to `5.21`. Before that date it was pointing to `5.20`. Please try again and watch your VM host being deployed successfully :slightly_smiling_face: 

```bash
$ snap info lxd
...
channels:
  5.21/stable:      5.21.1-3f3c2a9 2024-04-09 (28156) 107MB -
...
```
