### ISSUE TITLE
Support for timeouts for instance and machine resource

### ISSUE THREAD

**Issue by ageoffron** [maas/terraform-provider-maas#32]
Hitting timeout issue when awaiting for machine or instance to come up.
It seems timeout support in machine and instance resource for the Create operation is easy to implement..

Reference:
[terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/website/docs/plugin/sdkv2/resources/retries-and-customizable-timeouts.mdx)

Doing some testing, adding Timeouts to 
func resourceMaasInstance()  and func resourceMaasMachine()

looks like this:

```
Timeouts: &schema.ResourceTimeout{
  Create: schema.DefaultTimeout(20 * time.Minute),
},
```

with the terraform resource:

```
resource "maas_machine" "mymachine" {
  hostname   = "mymachine"
  power_type = "redfish"
  power_parameters = {
    power_address = "10.0.0.x"
    power_user    = ""
    power_pass    = ""
  }
  pxe_mac_address = ""
  
  timeouts {
    create = "35m"
  }
}
```

Happy to submit a PR..

**Comment by FunSkiDry** [comment]
Yes this is a much needed addition!  Are there still maintainers for this project?

**Comment by sparkiegeek** [comment]
@cpg1111 can we close this?

**Comment by cpg1111** [comment]
@sparkiegeek yeah, this fix has landed and been released, will close
