### ISSUE TITLE
How to register metal as MaaS KVM host?

### ISSUE THREAD

**Issue by bcdiaconu** [maas/terraform-provider-maas#40]
When deploying an (Ubuntu) OS to metals, how could I setup with `terraform-provider-maas` to `Register as MAAS KVM host`, such that it would behave like checking the box while deploying by use of the MaaS UI (please view the attached image)?

![image](https://user-images.githubusercontent.com/23461852/204480212-d60c270a-83e8-4f2c-ace3-709d77da0358.png)

**Comment by pescobar** [comment]
We are also interested in this functionality. Any chance that this feature gets implemented?

**Comment by mastier** [comment]
There's special VM Host resource for that purpose
https://github.com/maas/terraform-provider-maas/blob/927857f308537f27fa42c49ab4eb0cfc9697206f/examples/resources/maas_vm_host/resource.tf

and the actual vm machine that you can create there:
https://github.com/maas/terraform-provider-maas/blob/927857f308537f27fa42c49ab4eb0cfc9697206f/examples/resources/maas_vm_host_machine/resource.tf

But you have to deploy the kvm  host machine before that. Actually in MAAS these objects are decoupled. The IP for the URL is derived from the machine when created.
