### ISSUE TITLE
Custom commissioning scripts are not executed when adding machine via Terraform

### ISSUE THREAD

**Issue by tFable** [maas/terraform-provider-maas#51]
Hello,

When adding a machine via the MAAS Terraform provider, no custom commissioning scripts are executed, even if they are set to automatically execute.

This is different than the behavior of adding machines via the UI where all default and all `auto` commissioning scripts are executed upon adding a machine.

Is this a bug or expected behavior? If expected, how can we get the desired behavior when adding machines via the Terraform provider?

Thanks!
t

**Comment by r00ta** [comment]
I could not reproduce this. By default all the custom commissioning scripts should be executed. 

If you still experience this, feel free to reopen with more information.
