### ISSUE TITLE
Cannot use it with self signed ssl certificate

### ISSUE THREAD

**Issue by pescobar** [maas/terraform-provider-maas#56]
I have enabled TLS using `maas config-tls enable` with a self-signed certificate and I cannot connect to MAAS . I get this error:

```
x509: cannot validate certificate for 10.34.46.100 because it doesn't contain any IP SANs
```

It would be great if the provider config would allow a flag like `validate_certs = True|False`

**Comment by troyanov** [comment]
Can you try adding MAAS IP address to a [SAN](https://en.wikipedia.org/wiki/Subject_Alternative_Name) entry of your certificate?

I agree, having such a flag is a good idea, but it should be also supported by https://github.com/maas/gomaasclient

**Comment by pescobar** [comment]
If I update my ssl self-signed cert to add a SAN entry then I get ` x509: certificate signed by unknown authority`

I will try to add my CA to the host executing terraform but being able to use `validate_certs = False` in the terraform provider config would be more convenient

**Comment by sparkiegeek** [comment]
Is there a standard way in Terraform of skipping certificate validation?
