### ISSUE TITLE
terraform import fails when a specific MAAS feature is not supported in the provider

### ISSUE THREAD

**Issue by marosg42** [maas/terraform-provider-maas#68]
I have machines in MAAS which were configured with cache_sets using MAAS CLI.
When I do `terraform import maas_tag` import fails. I guess it will fail also for other not-yet supported setups like LVM.

```
$ terraform import maas_tag.foundation-nodes foundation-nodes -no-color

cannot unmarshal object into Go struct field Machine.cache_sets of type string
```

When I change the node not to use cache_set, import works fine

**Comment by troyanov** [comment]
Hi @marosg42 

Yes, indeed, there is an issue (type inconsistency in un/marshalling from JSON returned by MAAS API and Go structs) that should be fixed in the underlying `gomaasclient` package:
https://github.com/maas/gomaasclient/blob/433cd320a733c19f8344a5f624b769d0dd2a8944/entity/machine.go#L34

**Comment by skatsaounis** [comment]
Hi @marosg42

With this PR https://github.com/maas/terraform-provider-maas/pull/92, the new version of `gomaasclient` is used by the provider, which includes a fix on the parsing of field `cache_sets` among others.

Could you please try the new version of the provider `1.3.0` and let us know if the problem persists?
