### ISSUE TITLE
Publishing to the Terraform Public Registry

### ISSUE THREAD

**Issue by dan-sullivan** [maas/terraform-provider-maas#9]
Hi, thanks for the work on this. 
I'd like to know if/when you intend to publish it onto the public Terraform registry? Currently Ive had to fork it to use in my workflows from there.
Thanks

**Comment by proegssilb** [comment]
Bump.

I was just looking at the list of maas providers in the terraform registry, and there's a pretty significant credibility problem going on. Having an official, first-party, maintained terraform provider would make it a lot easier to figure out what I should be using.

**Comment by tmiller** [comment]
Bump. Again same problem as others. It would be really nice to have this published to the terraform registry from the official source.

**Comment by RomainL972** [comment]
I also think it would be really nice if this was published to Terraform. Here is the documentation if needed : https://www.terraform.io/registry/providers/publishing

**Comment by uberspot** [comment]
Is publishing the provider something that you intend to do? 
Forking seems like a sad way forward imho just to get the provider in the registry and be able to actually use it. :/

**Comment by CommanderTso** [comment]
Same.  Can this be added to the registry, please?

**Comment by rockpapergoat** [comment]
yes, please address issues with the provider and publish. we're looking to use this in a production setting and have to patch and build it to work around bugs.

**Comment by sparkiegeek** [comment]
https://registry.terraform.io/providers/maas/maas/latest

:dancers:
